import allure
from pages.form import FormPages, SubmitPages

@allure.description('Verify error field is empty')
def test_requirement_field(browser):
    action_form = FormPages(browser)
    action_form.verify_form_page()
    action_form.tap_submit_btn()
    action_form.verify_required_field()

@allure.description('Verify error field is invalid')
def test_invalid_field(browser):
    action_form = FormPages(browser)
    action_form.verify_form_page()
    action_form.input_first_name('Budi')
    action_form.input_last_name('Pekerti')
    action_form.input_email('budi@mail')
    action_form.select_gender('Female')
    action_form.input_mobile_number('asd123')
    action_form.tap_submit_btn()
    action_form.verify_invalid_field()

@allure.description('Verify clear subjects')
def test_clear_subject(browser):
    action_form = FormPages(browser)
    action_form.verify_form_page()
    action_form.input_first_name('Budi')
    action_form.input_last_name('Pekerti')
    action_form.input_email('budi@mail.com')
    action_form.select_gender('Female')
    action_form.input_mobile_number('1234512435')
    action_form.input_date_of_birth('20 Oct 1900')
    action_form.input_subject(['Arts','Commerce'])
    action_form.clear_subject()

@allure.description('Verify remove a subject')
def test_remove_subject(browser):
    action_form = FormPages(browser)
    action_form.verify_form_page()
    action_form.input_first_name('Budi')
    action_form.input_last_name('Pekerti')
    action_form.input_email('budi@mail.com')
    action_form.select_gender('Female')
    action_form.input_mobile_number('1234512435')
    action_form.input_date_of_birth('20 Oct 1900')
    action_form.input_subject(['Arts','Commerce'])
    action_form.remova_value_subject('Commerce')

@allure.description('Verify form register submit view modal')
def test_input_then_verify_form(browser):
    action_form = FormPages(browser)
    view_form = SubmitPages(browser)
    action_form.verify_form_page()
    action_form.input_first_name('Budi')
    action_form.input_last_name('Pekerti')
    action_form.input_email('budi@mail.com')
    action_form.select_gender('Female')
    action_form.input_mobile_number('1234512435')
    action_form.input_date_of_birth('20 Oct 1900')
    action_form.input_subject(['Arts','Commerce'])
    action_form.remova_value_subject('Arts')
    action_form.select_bobbies(['Sports','Music'])
    action_form.upload_picture()
    action_form.input_current_address('Complex Elite')
    action_form.select_state('Rajasthan')
    action_form.select_city('Jaiselmer')
    action_form.tap_submit_btn()
    view_form.verify_form_modal_page()
    view_form.tap_close_btn()