class FormLocators:
    header_form_page = "h5:text('Student Registration Form')"
    first_name_txt = "#firstName"
    last_name_txt = "#lastName"
    user_mail_txt = "#userEmail"
    select_gender = "input[name='gender']"
    gender_label = "label[for='gender-radio-{}']"
    gender_input = "#gender-radio-{}"
    mobile_number = "#userNumber"
    set_date_of_birth = "#dateOfBirthInput"
    input_subject = "#subjectsInput"
    subject_chip = ".subjects-auto-complete__multi-value__label"
    subject_opt = ".subjects-auto-complete__option"
    subject_chip = ".subjects-auto-complete__multi-value"
    remove_subject_value = ".subjects-auto-complete__multi-value__remove"
    clear_subject = ".subjects-auto-complete__clear-indicator"
    select_hobbies = "input[type='checkbox']"
    hobbies_label = "label[for='hobbies-checkbox-{}']"
    hobbies_input = "#hobbies-checkbox-{}"
    upload_picture = "#uploadPicture"
    current_address_txt = "#currentAddress"
    state_dropdown = "#state"
    select_state = "div[id^='react-select'][class*='option']"
    city_dropdown = "#city"
    select_city = "div[id^='react-select'][class*='option']"
    submit_btn = "#submit"

class SubmitLocators:
    header_modal = "#example-modal-sizes-title-lg"
    body_modal = "div.modal-content"
    close_btn = "#closeLargeModal"
